webtalk_init -webtalk_dir E:/courseproject_NCDC_cohort3/AXI2AHB_liteBridge/axi5_to_ahb5_lite_bridge/AXI5_to_AHB5_lite/AXI5_to_AHB5_lite.sim/sim_1/behav/xsim/xsim.dir/axi5_to_ahb5_lite_TOP_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 23 23:54:21 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e49122d0-508c-471e-8acb-71296aea7e50" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb0493ad88454dc8b4f15a2ea06608e7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "53" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8776_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1672130925 -regid "" -xml E:/courseproject_NCDC_cohort3/AXI2AHB_liteBridge/axi5_to_ahb5_lite_bridge/AXI5_to_AHB5_lite/AXI5_to_AHB5_lite.sim/sim_1/behav/xsim/xsim.dir/axi5_to_ahb5_lite_TOP_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/courseproject_NCDC_cohort3/AXI2AHB_liteBridge/axi5_to_ahb5_lite_bridge/AXI5_to_AHB5_lite/AXI5_to_AHB5_lite.sim/sim_1/behav/xsim/xsim.dir/axi5_to_ahb5_lite_TOP_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/courseproject_NCDC_cohort3/AXI2AHB_liteBridge/axi5_to_ahb5_lite_bridge/AXI5_to_AHB5_lite/AXI5_to_AHB5_lite.sim/sim_1/behav/xsim/xsim.dir/axi5_to_ahb5_lite_TOP_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
